object: orig/GM8E01_00/sys/main.dol
hash: 949c5ed7368aef547e0b0db1c3678f466e2afbff
symbols: config/GM8E01_00/symbols.txt
splits: config/GM8E01_00/splits.txt
mw_comment_version: 8
quick_analysis: true # Faster reruns after full analysis
fill_gaps: false # Alignments known

#modules:
#- object: orig/GM8E01_00/files/NESemuP.rel
  #hash: 5ad6bb727d6dd220e6aceef9143c61a86a6f2bb5
  #symbols: config/GM8E01_00/NESemu/symbols.txt
  #splits: config/GM8E01_00/NESemu/splits.txt
