"""Exports named data symbols from config/<VERSION>/symbols.txt, one file per version.

Keeps every named data object (vtables, globals, statics) and drops functions and
dtk's auto-generated names (lbl_*, @NNN, ...). Output lines are `0xADDRESS name`,
sorted by address.

--aliases adds extra names for existing symbols (e.g. for ones that are unnamed, or
whose name differs between versions). Each non-comment line of that file is
`<VERSION> <new name> <existing symbol>`.

Usage: python scripts/export_data_symbols.py -o OUT_DIR [--aliases FILE] VERSION...
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple

from symbols import parse_symbols_file

ROOT = Path(__file__).resolve().parent.parent
AUTO_NAME = re.compile(r"^(lbl_|@|jumptable_|gap_|\.\.\.)")


def load_aliases(path: Path, version: str) -> List[Tuple[str, str]]:
    aliases = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        alias_version, name, target = line.split()
        if alias_version == version:
            aliases.append((name, target))
    return aliases


def export(version: str, out_dir: Path, aliases_path: Optional[Path]) -> None:
    symbols = parse_symbols_file(ROOT / "config" / version / "symbols.txt")
    by_name = {s.name: s.address for s in symbols}
    kept = [
        (s.name, s.address)
        for s in symbols
        if s.attrs.get("type") == "object" and s.section != ".text" and not AUTO_NAME.match(s.name)
    ]

    if aliases_path is not None:
        names = {name for name, _ in kept}
        for name, target in load_aliases(aliases_path, version):
            if target not in by_name:
                sys.exit(f"{version}: alias {name} -> {target}: no such symbol")
            if name in names:
                sys.exit(f"{version}: alias {name} is already a symbol; drop the alias")
            kept.append((name, by_name[target]))

    kept.sort(key=lambda s: (s[1], s[0]))
    out = out_dir / f"{version}.txt"
    with out.open("w") as f:
        f.write(f"# Generated by prime-decomp scripts/export_data_symbols.py from config/{version}/symbols.txt\n")
        for name, address in kept:
            f.write(f"0x{address:08X} {name}\n")
    print(f"wrote {out} ({len(kept)} symbols)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("-o", "--out-dir", type=Path, required=True, help="writes <OUT_DIR>/<VERSION>.txt")
    parser.add_argument("--aliases", type=Path, help="extra names to add (see above)")
    parser.add_argument("versions", nargs="+", type=str.upper, metavar="VERSION")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for version in args.versions:
        export(version, args.out_dir, args.aliases)


if __name__ == "__main__":
    main()
