object_base: orig/R3ME01_00
object: files/rs5mp1_p.dol
hash: e6416b2f8b92fdd8ebeb1d53f133e96f5ca9763a
symbols: config/R3ME01_00/symbols.txt
splits: config/R3ME01_00/splits.txt
mw_comment_version: 8
#quick_analysis: true # Faster reruns after full analysis
#fill_gaps: false # Alignments known
