name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/primedecomp/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [GM8E01_00] # GM8E01_01, GM8E01_48
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Prepare
      run: cp -R /orig .
    - name: Build
      run: |
        python configure.py --map --version ${{matrix.version}} --compilers /compilers
        ninja
    - name: Upload progress
      if: github.ref == 'refs/heads/main' && matrix.version == 'GM8E01_00'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python tools/upload_progress.py -b https://progress.decomp.club/ -p prime -v ${{matrix.version}} \
          build/${{matrix.version}}/progress.json
    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.version}}_maps
        path: build/${{matrix.version}}/**/*.MAP
