name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install devkitPro
      run: |
        sudo dpkg --add-architecture i386
        curl -L https://apt.devkitpro.org/devkitpro-pub.gpg | sudo apt-key add -
        sudo add-apt-repository "deb https://apt.devkitpro.org stable main"
        sudo apt-get -y install devkitpro-pacman wine32
        sudo dkp-pacman -S --noconfirm gamecube-dev
    - uses: actions/checkout@v3
    - name: Download compilers
      run: |
        curl -L https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip \
          | bsdtar -xvf- -C tools --exclude Wii
        mv tools/GC tools/mwcc_compiler
    - name: make
      run: make -j
